main:
  components_repository: "https://github.com/CAMM961001/inai-itam"
  project_name: inai_google_trends
  steps: all
  tema: {"verde":"#00715F", "morado":"#6F197A"}
datos:
  criterios: "datos/bruto/criterios_busqueda.txt"
  corpus: "datos/procesados/salidas_trends_api.json"
  region: "datos/bruto/interes_region.json"
  tiempo: "datos/bruto/interes_tiempo.json"
  relacionados: "datos/bruto/temas_relacionados.json"
logs:
  etl: "logs/etl.log"
etl:
  anios: 2
  meses: 2
  relacionados: "datos/procesados/temas_relacionados.json"