main:
  components_repository: "https://github.com/CAMM961001/inai-itam"
  project_name: inai_google_trends
  steps: all
datos:
  criterios: "activos/criterios_busqueda.txt" #proto
  corpus: "datos/procesados/salidas_trends_api.json"
logs:
  etl: "logs/etl.log"
etl:
  corpus: "datos/procesados/salidas_trends_api.json"
  log: "activos/log_consulta.csv"