main:
  components_repository: "https://github.com/CAMM961001/inai-itam"
  project_name: inai_google_trends
  steps: all
datos:
  criterios: "datos/bruto/proto.txt" #criterios_busqueda
logs:
etl:
  corpus: "datos/procesados/salidas_trends_api.json"
  log: "activos/log_consulta.csv"